# Pegasus system definition — edit freely; consumed by deploy.sh
SYS_SHORTNAME="amiga"
SYS_NAME="Commodore Amiga"
SYS_DIRNAME="amiga"
SYS_EMULATOR="retroarch"
SYS_EXTENSIONS="adf, hdf, lha, ipf, uae, zip"
SYS_RA_CORE="puae"
