# Pegasus system definition — edit freely; consumed by deploy.sh
SYS_SHORTNAME="c64"
SYS_NAME="Commodore 64"
SYS_DIRNAME="c64"
SYS_EMULATOR="retroarch"
SYS_EXTENSIONS="d64, t64, crt, prg, tap, g64, zip"
SYS_RA_CORE="vice_x64sc"
