# Pegasus system definition — edit freely; consumed by deploy.sh
SYS_SHORTNAME="dreamcast"
SYS_NAME="Sega Dreamcast"
SYS_DIRNAME="dreamcast"
SYS_EMULATOR="retroarch"
SYS_EXTENSIONS="cdi, gdi, chd, cue, m3u"
SYS_RA_CORE="flycast"
