# Pegasus system definition — edit freely; consumed by deploy.sh
SYS_SHORTNAME="gamecube"
SYS_NAME="Nintendo GameCube"
SYS_DIRNAME="gamecube"
SYS_EMULATOR="dolphin"
SYS_EXTENSIONS="iso, rvz, gcm, ciso, gcz"
SYS_RA_CORE=""
