# Pegasus system definition — edit freely; consumed by deploy.sh
SYS_SHORTNAME="gb"
SYS_NAME="Nintendo Game Boy"
SYS_DIRNAME="gb"
SYS_EMULATOR="retroarch"
SYS_EXTENSIONS="gb, zip"
SYS_RA_CORE="gambatte"
