# Pegasus system definition — edit freely; consumed by deploy.sh
SYS_SHORTNAME="gba"
SYS_NAME="Nintendo Game Boy Advance"
SYS_DIRNAME="gba"
SYS_EMULATOR="retroarch"
SYS_EXTENSIONS="gba, zip"
SYS_RA_CORE="mgba"
