# Pegasus system definition — edit freely; consumed by deploy.sh
SYS_SHORTNAME="gbc"
SYS_NAME="Nintendo Game Boy Color"
SYS_DIRNAME="gbc"
SYS_EMULATOR="retroarch"
SYS_EXTENSIONS="gbc, zip"
SYS_RA_CORE="gambatte"
