# Pegasus system definition — edit freely; consumed by deploy.sh
SYS_SHORTNAME="mastersystem"
SYS_NAME="Sega Master System"
SYS_DIRNAME="mastersystem"
SYS_EMULATOR="retroarch"
SYS_EXTENSIONS="sms, zip"
SYS_RA_CORE="genesis_plus_gx"
