# Pegasus system definition — edit freely; consumed by deploy.sh
SYS_SHORTNAME="megadrive"
SYS_NAME="Sega Mega Drive / Genesis"
SYS_DIRNAME="megadrive"
SYS_EMULATOR="retroarch"
SYS_EXTENSIONS="md, bin, gen, smd, zip"
SYS_RA_CORE="genesis_plus_gx"
