# Pegasus system definition — edit freely; consumed by deploy.sh
SYS_SHORTNAME="n64"
SYS_NAME="Nintendo 64"
SYS_DIRNAME="n64"
SYS_EMULATOR="retroarch"
SYS_EXTENSIONS="n64, z64, v64, zip"
SYS_RA_CORE="mupen64plus_next"
