# Pegasus system definition — edit freely; consumed by deploy.sh
SYS_SHORTNAME="neogeo"
SYS_NAME="SNK Neo Geo"
SYS_DIRNAME="neogeo"
SYS_EMULATOR="retroarch"
SYS_EXTENSIONS="zip, neo, chd"
SYS_RA_CORE="fbneo"
