# Pegasus system definition — edit freely; consumed by deploy.sh
SYS_SHORTNAME="pcengine"
SYS_NAME="NEC PC Engine / TurboGrafx-16"
SYS_DIRNAME="pcengine"
SYS_EMULATOR="retroarch"
SYS_EXTENSIONS="pce, cue, chd, zip"
SYS_RA_CORE="mednafen_pce"
