# Pegasus system definition — edit freely; consumed by deploy.sh
SYS_SHORTNAME="ps2"
SYS_NAME="Sony PlayStation 2"
SYS_DIRNAME="ps2"
SYS_EMULATOR="pcsx2"
SYS_EXTENSIONS="iso, chd, cso, bin, mdf, gz"
SYS_RA_CORE=""
