# Pegasus system definition — edit freely; consumed by deploy.sh
SYS_SHORTNAME="psp"
SYS_NAME="Sony PlayStation Portable"
SYS_DIRNAME="psp"
SYS_EMULATOR="ppsspp"
SYS_EXTENSIONS="iso, cso, pbp, chd"
SYS_RA_CORE=""
