# Pegasus system definition — edit freely; consumed by deploy.sh
SYS_SHORTNAME="psx"
SYS_NAME="Sony PlayStation"
SYS_DIRNAME="psx"
SYS_EMULATOR="duckstation"
SYS_EXTENSIONS="cue, chd, pbp, m3u, ecm"
SYS_RA_CORE=""
