# Pegasus system definition — edit freely; consumed by deploy.sh
SYS_SHORTNAME="saturn"
SYS_NAME="Sega Saturn"
SYS_DIRNAME="saturn"
SYS_EMULATOR="retroarch"
SYS_EXTENSIONS="cue, chd, m3u, ccd, iso, zip"
SYS_RA_CORE="mednafen_saturn"
