# Pegasus system definition — edit freely; consumed by deploy.sh
SYS_SHORTNAME="scummvm"
SYS_NAME="ScummVM Adventure Games"
SYS_DIRNAME="scummvm"
SYS_EMULATOR="scummvm"
SYS_EXTENSIONS="scummvm"
SYS_RA_CORE=""
