# Pegasus system definition — edit freely; consumed by deploy.sh
SYS_SHORTNAME="snes"
SYS_NAME="Super Nintendo Entertainment System"
SYS_DIRNAME="snes"
SYS_EMULATOR="retroarch"
SYS_EXTENSIONS="sfc, smc, zip, 7z"
SYS_RA_CORE="snes9x"
