# Pegasus system definition — edit freely; consumed by deploy.sh
SYS_SHORTNAME="vita"
SYS_NAME="Sony PlayStation Vita"
SYS_DIRNAME="vita"
SYS_EMULATOR="vita3k"
SYS_EXTENSIONS="vpk, zip"
SYS_RA_CORE=""
