# Pegasus system definition — edit freely; consumed by deploy.sh
SYS_SHORTNAME="wii"
SYS_NAME="Nintendo Wii"
SYS_DIRNAME="wii"
SYS_EMULATOR="dolphin"
SYS_EXTENSIONS="iso, rvz, wbfs, wad"
SYS_RA_CORE=""
