# Pegasus system definition — edit freely; consumed by deploy.sh
SYS_SHORTNAME="wiiu"
SYS_NAME="Nintendo Wii U"
SYS_DIRNAME="wiiu"
SYS_EMULATOR="cemu"
SYS_EXTENSIONS="wud, wux, wua, rpx, elf"
SYS_RA_CORE=""
