# Pegasus system definition — edit freely; consumed by deploy.sh
SYS_SHORTNAME="wonderswan"
SYS_NAME="Bandai WonderSwan"
SYS_DIRNAME="wonderswan"
SYS_EMULATOR="retroarch"
SYS_EXTENSIONS="ws, wsc, zip"
SYS_RA_CORE="mednafen_wswan"
